### ISSUE TITLE
How to follow a link ?

### ISSUE THREAD

**Issue by KevinNadaud** [dragly/latex-hyperclick#4]
Hi,
I would like to know how to follow a link to a file or a reference using this package ? If I made right click on there is nothing in the popup menu to follow the link. Do I need to activate something else ?

Cheer

**Comment by KevinNadaud** [comment]
OK, it works. I forget to install hyperclick package !
Maybe, add this into the help ?

**Comment by dragly** [comment]
Thanks for the heads up! I will add a dependency on hyperclick next time I'm working on this package.
